#配置数据源属性
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.28.182:3306/culture?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    druid:
      max-active: 20
      max-wait: 5000
      initial-size: 5
      validation-query: select 1

      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        allow:
        deny:
        url-pattern: "/druid/*"

  #thymeleaf
  thymeleaf:
    cache: false
    enabled: true
  #      web-stat-filter:
  #        enabled: true
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:/C:/Users/Administrator/Desktop

  #redis
  redis:
    host: 101.37.28.182
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    timeout: 2000ms
  cache:
    type: REDIS

  #以下是我设置的session过期时间
  #session share  unit hours(设置成分钟方便测试)
  session:
    timeout: 3000s

# 配置mybatis plus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /res/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-urls:
    - /**